# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cac32d7a94196c7bfa956a7c3f8f09553a7e4332dbe5727e5dce1ae34ef0213e272b31fa7a77b26fb6b64335c4bdb06fbdaf7c13bcc3ee41ae638a3c6fc2faa

test:
  secret_key_base: eaf940e078ec2dddfd25139d694e2e21b85d648f06ceb242c91601b1a4c4909922c7024d7c321e623ea0168023af4dfd53088724b14e61a5ee3ac32db0b3b8f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
